/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentRouteImport } from './routes/treatment'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DiseasePreventionRouteImport } from './routes/disease-prevention'
import { Route as DietLifestyleRouteImport } from './routes/diet-lifestyle'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TreatmentRoute = TreatmentRouteImport.update({
  id: '/treatment',
  path: '/treatment',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasePreventionRoute = DiseasePreventionRouteImport.update({
  id: '/disease-prevention',
  path: '/disease-prevention',
  getParentRoute: () => rootRouteImport,
} as any)
const DietLifestyleRoute = DietLifestyleRouteImport.update({
  id: '/diet-lifestyle',
  path: '/diet-lifestyle',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/diet-lifestyle': typeof DietLifestyleRoute
  '/disease-prevention': typeof DiseasePreventionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/treatment': typeof TreatmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/diet-lifestyle': typeof DietLifestyleRoute
  '/disease-prevention': typeof DiseasePreventionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/treatment': typeof TreatmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/diet-lifestyle': typeof DietLifestyleRoute
  '/disease-prevention': typeof DiseasePreventionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/treatment': typeof TreatmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/diet-lifestyle'
    | '/disease-prevention'
    | '/sitemap.xml'
    | '/studio'
    | '/treatment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/diet-lifestyle'
    | '/disease-prevention'
    | '/sitemap.xml'
    | '/studio'
    | '/treatment'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/diet-lifestyle'
    | '/disease-prevention'
    | '/sitemap.xml'
    | '/studio'
    | '/treatment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DietLifestyleRoute: typeof DietLifestyleRoute
  DiseasePreventionRoute: typeof DiseasePreventionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  TreatmentRoute: typeof TreatmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatment': {
      id: '/treatment'
      path: '/treatment'
      fullPath: '/treatment'
      preLoaderRoute: typeof TreatmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-prevention': {
      id: '/disease-prevention'
      path: '/disease-prevention'
      fullPath: '/disease-prevention'
      preLoaderRoute: typeof DiseasePreventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet-lifestyle': {
      id: '/diet-lifestyle'
      path: '/diet-lifestyle'
      fullPath: '/diet-lifestyle'
      preLoaderRoute: typeof DietLifestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DietLifestyleRoute: DietLifestyleRoute,
  DiseasePreventionRoute: DiseasePreventionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  TreatmentRoute: TreatmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
